export const actions = [
    'Add',
    'Allow to chill',
    'Assemble',
    'Bake',
    'Beat',
    'Blend',
    'Boil',
    'Break',
    'Bring to a boil',
    'Carve',
    'Chill',
    'Chop',
    'Coat',
    'Combine',
    'Cook',
    'Crack',
    'Crush',
    'Cut',
    'Cut out',
    'Deep fry',
    'Defrost',
    'Dehydrate',
    'Dice',
    'Discard the skin',
    'Divide',
    'Drain',
    'Drizzle',
    'Fill (with)',
    'Flatten',
    'Freeze',
    'Froth',
    'Fry',
    'Garnish (with)',
    'Glaze',
    'Grate',
    'Grill',
    'Grind',
    'Heat',
    'Knead',
    'Marinate',
    'Mash',
    'Melt',
    'Microwave',
    'Mince',
    'Mix',
    'Pair with',
    'Peel',
    'Place',
    'Poke holes',
    'Pour',
    'Pour',
    'Preheat oven',
    'Prepare',
    'Process (until well combined)',
    'Refrigerate',
    'Remove (from mold)',
    'Rinse',
    'Roast',
    'Roll',
    'Sauté',
    'Season',
    'Shake',
    'Sieve',
    'Sift',
    'Simmer',
    'Slice (off)',
    'Smell',
    'Soak',
    'Spray',
    'Spread',
    'Sprinkle',
    'Squeeze',
    'Steam',
    'Stir',
    'Stir fry',
    'Strain',
    'Taste',
    'Thaw',
    'Toast',
    'Top (with)',
    'Toss',
    'Toss',
    'Transfer',
    'Weight',
    'Whisk',
    'Wrap',
]
