export const actions = [
    'Slice (off)',
    'Place',
    'Toss',
    'Rinse',
    'Soak',
    'Mince',
    'Cut',
    'Chop',
    'Freeze',
    'Defrost',
    'Dehydrate',
    'Strain',
    'Add',
    'Mix',
    'Bake',
    'Fry',
    'Deep fry',
    'Boil',
    'Refrigerate',
    'Toss',
    'Remove (from mold)',
    'Peel',
    'Discard the skin',
    'Bring to a boil',
    'Taste',
    'Cook',
    'Sprinkle',
    'Preheat oven',
    'Microwave',
    'Poke holes',
    'Wrap',
    'Mash',
    'Sauté',
    'Fill (with)',
    'Top (with)',
    'Combine',
    'Toast',
    'Roast',
    'Grill',
    'Drain',
    'Coat',
    'Stir fry',
    'Transfer',
    'Prepare',
    'Garnish (with)',
    'Heat',
    'Season',
    'Shake',
    'Pour',
    'Squeeze',
    'Divide',
    'Grind',
    'Blend',
    'Chill',
    'Assemble',
    'Melt',
    'Roll',
    'Sift',
    'Glaze',
    'Spray',
    'Spread',
    'Knead',
    'Break',
    'Whisk',
    'Grate',
    'Dice',
    'Stir',
    'Flatten',
    'Simmer',
    'Sieve',
    'Carve',
    'Pour',
    'Drizzle',
    'Cut out',
    'Crush',
    'Crack',
    'Smell',
    'Weight',
    'Beat',
    'Process (until well combined)',
    'Steam',
    'Marinate',
    'Pair with',
    'Froth',
    'Allow to chill',
]
